version: "3"

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - cars_api

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENERS_LISTENERS=yes
    networks:
      - cars_api
    depends_on:
      - zookeeper

  mongodb:
    image: bitnami/mongodb:latest
    user: root
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/bitnami/mongodb

networks:
  cars_api:
